site_name: 'Geralt'

# Navigation
nav:
  - Getting Started: index.md
  - Development: mkdocs/development.md
  - Application Mode: mkdocs/application-mode.md
  - Observability: mkdocs/observability.md

plugins:
  - techdocs-core